## p;o
GET http://localhost:8080/

### ping
GET http://localhost:8080/ping

### get all user
GET http://localhost:8080/users/all

### get user
GET http://localhost:8080/users/1

### register user
POST http://localhost:8080/user/create
Content-Type: application/json

{
  "name": "test",
  "email": "hi@hello.com"
}